### ISSUE TITLE
guava

### ISSUE THREAD

**Issue by flynet** [openengsb/openengsb-wrapped-com.atlassian.jira.rest.client#3]
Hello,
java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;

	at com.atlassian.jira.rest.client.api.domain.BasicIssue.getToStringHelper(BasicIssue.java:71)
	at com.atlassian.jira.rest.client.api.domain.Issue.getToStringHelper(Issue.java:358)
	at com.atlassian.jira.rest.client.api.domain.BasicIssue.toString(BasicIssue.java:67)

Please, assist, it conflicts with guava 23

**Comment by kristofmeixner** [comment]
Do you use it in an OSGi container or just as dependency in another project?
